definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: Sample of WebApiRest_Golang
  license:
    name: MIT
    url: https://github1.com/CastroEduardo/golang-api-rest/blob/master/LICENSE
  termsOfService: https://github1.com/CastroEduardo/golang-api-rest
  title: Golang Gin API
  version: "2.0"
paths:
  /api/v1/articles/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Get a single article
      tags:
      - v1 Articles
  /api/v2/articles/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Get a single article
      tags:
      - Api-v2
  /api/v2/manageDepartment:
    post:
      parameters:
      - description: typeOperation
        in: query
        name: typeOperation
        required: true
        type: string
      - description: idParam
        in: query
        name: idParam
        required: true
        type: string
      - description: modelJson
        in: query
        name: modelJson
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Manage DepartamentUser Sys
      tags:
      - Api-v2
  /api/v2/managedGenericOptions:
    post:
      parameters:
      - description: modelOptions
        in: query
        name: modelOptions
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: ManagedGenericOptions Sys
      tags:
      - Api-v2
  /api/v2/managedUserSys:
    post:
      parameters:
      - description: modelUser
        in: query
        name: modelUser
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Add user to System
      tags:
      - Api-v2
  /api/v2/manageduploadfiles:
    post:
      parameters:
      - description: modelUser
        in: query
        name: modelUser
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Upload Files to Server
      tags:
      - Api-v2
  /api/v2/manageprivilegesys:
    post:
      parameters:
      - description: typeOperation
        in: query
        name: typeOperation
        required: true
        type: string
      - description: idParam
        in: query
        name: idParam
        required: true
        type: string
      - description: modelJson
        in: query
        name: modelJson
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Manage Privilege Sys
      tags:
      - Api-v2
  /api/v2/managerolsys:
    post:
      parameters:
      - description: typeOperation
        in: query
        name: typeOperation
        required: true
        type: string
      - description: idParam
        in: query
        name: idParam
        required: true
        type: string
      - description: modelJson
        in: query
        name: modelJson
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Manage RolesUser Sys
      tags:
      - Api-v2
  /api/v2/userlistsys:
    post:
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Get list userSys
      tags:
      - Api-v2
  /auth:
    get:
      operationId: Authentication
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      - description: remember
        in: query
        name: remember
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get Auth
      tags:
      - Auth
    post:
      operationId: Authentication
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      - description: remember
        in: query
        name: remember
        required: true
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Post Auth
      tags:
      - Auth
  /auth/checkIdDevice:
    post:
      parameters:
      - description: idDevice
        in: query
        name: idDevice
        required: true
        type: string
      - description: type
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
      summary: Post CheckIdDevice
      tags:
      - Auth
  /auth/checkpassword:
    post:
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Post Check Password User
      tags:
      - Auth
  /auth/checkstatustoken:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Post ClaimUser
      tags:
      - Auth
  /auth/claim-user:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Post ClaimUser
      tags:
      - Auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - bearerAuth: []
      summary: Post ClaimUser
      tags:
      - Auth
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
